package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AudiciaReportSpec defines the identity context for a compliance report.
// This contains the subject the report covers. Set once when created.
type AudiciaReportSpec struct {
	// Subject identifies who this report is about.
	// +kubebuilder:validation:Required
	Subject Subject `json:"subject"`
}

// AudiciaReportStatus contains compliance scoring and observed RBAC usage.
type AudiciaReportStatus struct {
	// ObservedRules is the structured list of observed RBAC rules for this subject.
	// +optional
	ObservedRules []ObservedRule `json:"observedRules,omitempty"`

	// Compliance contains the RBAC drift analysis comparing observed usage
	// against the subject's effective permissions in the cluster.
	// +optional
	Compliance *ComplianceReport `json:"compliance,omitempty"`

	// EventsProcessed is the total number of audit events that contributed to this report.
	// +optional
	EventsProcessed int64 `json:"eventsProcessed,omitempty"`

	// LastProcessedTime is the timestamp of the last processed event for this subject.
	// +optional
	LastProcessedTime *metav1.Time `json:"lastProcessedTime,omitempty"`

	// Conditions represent the latest available observations of the report's state.
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:shortName=areport
// +kubebuilder:printcolumn:name="Subject",type=string,JSONPath=`.spec.subject.name`
// +kubebuilder:printcolumn:name="Kind",type=string,JSONPath=`.spec.subject.kind`
// +kubebuilder:printcolumn:name="Compliance",type=string,JSONPath=`.status.compliance.severity`
// +kubebuilder:printcolumn:name="Score",type=integer,JSONPath=`.status.compliance.score`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`
// +kubebuilder:printcolumn:name="Needed",type=integer,JSONPath=`.status.compliance.usedCount`,priority=1,description="RBAC rules actually exercised"
// +kubebuilder:printcolumn:name="Excess",type=integer,JSONPath=`.status.compliance.excessCount`,priority=1,description="RBAC rules granted but never used"
// +kubebuilder:printcolumn:name="Ungranted",type=integer,JSONPath=`.status.compliance.uncoveredCount`,priority=1,description="observed actions without RBAC grant"
// +kubebuilder:printcolumn:name="Sensitive",type=boolean,JSONPath=`.status.compliance.hasSensitiveExcess`,priority=1,description="excess grants on sensitive resources"
// +kubebuilder:printcolumn:name="Audit Events",type=integer,JSONPath=`.status.eventsProcessed`,priority=1,description="total audit events processed"

// AudiciaReport contains the observed RBAC rules and compliance scoring
// for a single subject, generated by the Audicia operator.
type AudiciaReport struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AudiciaReportSpec   `json:"spec,omitempty"`
	Status AudiciaReportStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AudiciaReportList contains a list of AudiciaReport resources.
type AudiciaReportList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AudiciaReport `json:"items"`
}
