//go:build !ignore_autogenerated

/*
Copyright 2026 The Audicia Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSCloudWatchConfig) DeepCopyInto(out *AWSCloudWatchConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSCloudWatchConfig.
func (in *AWSCloudWatchConfig) DeepCopy() *AWSCloudWatchConfig {
	if in == nil {
		return nil
	}
	out := new(AWSCloudWatchConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AudiciaPolicyReport) DeepCopyInto(out *AudiciaPolicyReport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AudiciaPolicyReport.
func (in *AudiciaPolicyReport) DeepCopy() *AudiciaPolicyReport {
	if in == nil {
		return nil
	}
	out := new(AudiciaPolicyReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AudiciaPolicyReport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AudiciaPolicyReportList) DeepCopyInto(out *AudiciaPolicyReportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AudiciaPolicyReport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AudiciaPolicyReportList.
func (in *AudiciaPolicyReportList) DeepCopy() *AudiciaPolicyReportList {
	if in == nil {
		return nil
	}
	out := new(AudiciaPolicyReportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AudiciaPolicyReportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AudiciaPolicyReportSpec) DeepCopyInto(out *AudiciaPolicyReportSpec) {
	*out = *in
	out.Subject = in.Subject
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AudiciaPolicyReportSpec.
func (in *AudiciaPolicyReportSpec) DeepCopy() *AudiciaPolicyReportSpec {
	if in == nil {
		return nil
	}
	out := new(AudiciaPolicyReportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AudiciaPolicyReportStatus) DeepCopyInto(out *AudiciaPolicyReportStatus) {
	*out = *in
	if in.ObservedRules != nil {
		in, out := &in.ObservedRules, &out.ObservedRules
		*out = make([]ObservedRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SuggestedPolicy != nil {
		in, out := &in.SuggestedPolicy, &out.SuggestedPolicy
		*out = new(SuggestedPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Compliance != nil {
		in, out := &in.Compliance, &out.Compliance
		*out = new(ComplianceReport)
		(*in).DeepCopyInto(*out)
	}
	if in.LastProcessedTime != nil {
		in, out := &in.LastProcessedTime, &out.LastProcessedTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AudiciaPolicyReportStatus.
func (in *AudiciaPolicyReportStatus) DeepCopy() *AudiciaPolicyReportStatus {
	if in == nil {
		return nil
	}
	out := new(AudiciaPolicyReportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AudiciaSource) DeepCopyInto(out *AudiciaSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AudiciaSource.
func (in *AudiciaSource) DeepCopy() *AudiciaSource {
	if in == nil {
		return nil
	}
	out := new(AudiciaSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AudiciaSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AudiciaSourceList) DeepCopyInto(out *AudiciaSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AudiciaSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AudiciaSourceList.
func (in *AudiciaSourceList) DeepCopy() *AudiciaSourceList {
	if in == nil {
		return nil
	}
	out := new(AudiciaSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AudiciaSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AudiciaSourceSpec) DeepCopyInto(out *AudiciaSourceSpec) {
	*out = *in
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(FileLocation)
		**out = **in
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(WebhookConfig)
		**out = **in
	}
	if in.Cloud != nil {
		in, out := &in.Cloud, &out.Cloud
		*out = new(CloudConfig)
		(*in).DeepCopyInto(*out)
	}
	out.PolicyStrategy = in.PolicyStrategy
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]Filter, len(*in))
		copy(*out, *in)
	}
	out.Checkpoint = in.Checkpoint
	out.Limits = in.Limits
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AudiciaSourceSpec.
func (in *AudiciaSourceSpec) DeepCopy() *AudiciaSourceSpec {
	if in == nil {
		return nil
	}
	out := new(AudiciaSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AudiciaSourceStatus) DeepCopyInto(out *AudiciaSourceStatus) {
	*out = *in
	if in.LastTimestamp != nil {
		in, out := &in.LastTimestamp, &out.LastTimestamp
		*out = (*in).DeepCopy()
	}
	if in.CloudCheckpoint != nil {
		in, out := &in.CloudCheckpoint, &out.CloudCheckpoint
		*out = new(CloudCheckpointStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AudiciaSourceStatus.
func (in *AudiciaSourceStatus) DeepCopy() *AudiciaSourceStatus {
	if in == nil {
		return nil
	}
	out := new(AudiciaSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureEventHubConfig) DeepCopyInto(out *AzureEventHubConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureEventHubConfig.
func (in *AzureEventHubConfig) DeepCopy() *AzureEventHubConfig {
	if in == nil {
		return nil
	}
	out := new(AzureEventHubConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointConfig) DeepCopyInto(out *CheckpointConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointConfig.
func (in *CheckpointConfig) DeepCopy() *CheckpointConfig {
	if in == nil {
		return nil
	}
	out := new(CheckpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudCheckpointStatus) DeepCopyInto(out *CloudCheckpointStatus) {
	*out = *in
	if in.PartitionOffsets != nil {
		in, out := &in.PartitionOffsets, &out.PartitionOffsets
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudCheckpointStatus.
func (in *CloudCheckpointStatus) DeepCopy() *CloudCheckpointStatus {
	if in == nil {
		return nil
	}
	out := new(CloudCheckpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudConfig) DeepCopyInto(out *CloudConfig) {
	*out = *in
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(AzureEventHubConfig)
		**out = **in
	}
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		*out = new(AWSCloudWatchConfig)
		**out = **in
	}
	if in.GCP != nil {
		in, out := &in.GCP, &out.GCP
		*out = new(GCPPubSubConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudConfig.
func (in *CloudConfig) DeepCopy() *CloudConfig {
	if in == nil {
		return nil
	}
	out := new(CloudConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceReport) DeepCopyInto(out *ComplianceReport) {
	*out = *in
	if in.SensitiveExcess != nil {
		in, out := &in.SensitiveExcess, &out.SensitiveExcess
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.LastEvaluatedTime.DeepCopyInto(&out.LastEvaluatedTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceReport.
func (in *ComplianceReport) DeepCopy() *ComplianceReport {
	if in == nil {
		return nil
	}
	out := new(ComplianceReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileLocation) DeepCopyInto(out *FileLocation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileLocation.
func (in *FileLocation) DeepCopy() *FileLocation {
	if in == nil {
		return nil
	}
	out := new(FileLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Filter) DeepCopyInto(out *Filter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Filter.
func (in *Filter) DeepCopy() *Filter {
	if in == nil {
		return nil
	}
	out := new(Filter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPPubSubConfig) DeepCopyInto(out *GCPPubSubConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPPubSubConfig.
func (in *GCPPubSubConfig) DeepCopy() *GCPPubSubConfig {
	if in == nil {
		return nil
	}
	out := new(GCPPubSubConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimitsConfig) DeepCopyInto(out *LimitsConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitsConfig.
func (in *LimitsConfig) DeepCopy() *LimitsConfig {
	if in == nil {
		return nil
	}
	out := new(LimitsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedRule) DeepCopyInto(out *ObservedRule) {
	*out = *in
	if in.APIGroups != nil {
		in, out := &in.APIGroups, &out.APIGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Verbs != nil {
		in, out := &in.Verbs, &out.Verbs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NonResourceURLs != nil {
		in, out := &in.NonResourceURLs, &out.NonResourceURLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.FirstSeen.DeepCopyInto(&out.FirstSeen)
	in.LastSeen.DeepCopyInto(&out.LastSeen)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedRule.
func (in *ObservedRule) DeepCopy() *ObservedRule {
	if in == nil {
		return nil
	}
	out := new(ObservedRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyStrategy) DeepCopyInto(out *PolicyStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyStrategy.
func (in *PolicyStrategy) DeepCopy() *PolicyStrategy {
	if in == nil {
		return nil
	}
	out := new(PolicyStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Subject) DeepCopyInto(out *Subject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Subject.
func (in *Subject) DeepCopy() *Subject {
	if in == nil {
		return nil
	}
	out := new(Subject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuggestedPolicy) DeepCopyInto(out *SuggestedPolicy) {
	*out = *in
	if in.Manifests != nil {
		in, out := &in.Manifests, &out.Manifests
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuggestedPolicy.
func (in *SuggestedPolicy) DeepCopy() *SuggestedPolicy {
	if in == nil {
		return nil
	}
	out := new(SuggestedPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookConfig) DeepCopyInto(out *WebhookConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookConfig.
func (in *WebhookConfig) DeepCopy() *WebhookConfig {
	if in == nil {
		return nil
	}
	out := new(WebhookConfig)
	in.DeepCopyInto(out)
	return out
}
